# Generated by Django 3.0.6 on 2020-05-31 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_que',
            name='gans',
        ),
    ]
