# Generated by Django 3.0.6 on 2020-05-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizUser', '0002_remove_quiz_que_gans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_que',
            name='question',
            field=models.TextField(max_length=200),
        ),
    ]
