# Generated by Django 3.0.6 on 2020-05-31 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizUser', '0003_auto_20200531_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_que',
            old_name='answer1',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='quiz_que',
            old_name='answer2',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='quiz_que',
            old_name='answer3',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='quiz_que',
            old_name='answer4',
            new_name='D',
        ),
    ]
