# Generated by Django 3.0.6 on 2020-06-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizUser', '0005_quiz_que_gans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_que',
            name='gans',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
