# Generated by Django 3.0.6 on 2020-06-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizUser', '0006_auto_20200601_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_que',
            name='qno',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
