# Generated by Django 3.0.6 on 2020-06-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizUser', '0007_quiz_que_qno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_que',
            name='id',
        ),
        migrations.AlterField(
            model_name='quiz_que',
            name='qno',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
